### ISSUE TITLE
Cut down size of Docker image

### ISSUE THREAD

**Issue by jwallwork23** [mesh-adaptation/docs#13]
The bespoke Firedrake Docker image we use is now almost 10GB... it is becoming very unwieldy. It would be great if we could cut down its size.

A few possible approaches:
* Apply optimisations such as those that Spack applies when it generates Docker images from `spack.yaml` files.
* Use `FROM ... AS builder` to strip out unnecessary stuff.

**Comment by jwallwork23** [comment]
Tried out some of the stuff here but didn't make much progress: https://dev.to/mattdark/python-docker-image-optimization-50p0.

**Comment by ddundo** [comment]
You said that I can take over issues without checking with you first :) hope it's okay that I did. Was curious about this

**Comment by jwallwork23** [comment]
> You said that I can take over issues without checking with you first :) hope it's okay that I did. Was curious about this

Much appreciated!
