### ISSUE TITLE
Build docs as part of CI

### ISSUE THREAD

**Issue by jwallwork23** [mesh-adaptation/docs#4]
Whilst working on pyroteus/pyroteus#119 I found a bug in the docs build. We could catch this sooner by adding a test that the docs build successfully.

**Comment by ddundo** [comment]
I'm interested in learning how to do this, so I'm happy to take it on. @jwallwork23 could you please tell me how you build and deploy the website currently?

**Comment by jwallwork23** [comment]
That'd be amazing, thanks @ddundo! Current process as follows:

1. Clone docs repo into ${VIRTUAL_ENV}/src
2. Clone mesh-adaptation.github.io repo as ${VIRTUAL_ENV}/src/mesh-adaptation-www
3. mkdir -p/build
4. ln -s ${VIRTUAL_ENV}/src/mesh-adaptation-www ${VIRTUAL_ENV}/src/mesh-adaptation-docs/build/html
5. cd ${VIRTUAL_ENV}/src/mesh-adaptation-docs/docs && make html

That should build the HTML docs in the www repo. Go there, check it's okay in your browser, and then commit the changes and push to the main branch.

**Comment by jwallwork23** [comment]
If that's not already in the wiki it should be added. (Even if it's automated it's still good to document the manual approach in case someone needs to do it.)

**Comment by ddundo** [comment]
Great, thanks for that!

**Comment by ddundo** [comment]
Blocked by #58
