### ISSUE TITLE
Avoid `ENV` warning for newer Docker installs

### ISSUE THREAD

**Issue by jwallwork23** [mesh-adaptation/docs#42]
This and other `ENV` lines raise a warning now: `LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value"`

_Originally posted by @ddundo in https://github.com/mesh-adaptation/mesh-adaptation-docs/pull/40#discussion_r1745394810_

**Comment by ddundo** [comment]
The CI now raises this warning as well: https://github.com/mesh-adaptation/mesh-adaptation-docs/actions/runs/11641745615/job/32420579075#step:5:653

Maybe fix this as part of #59 since it's minor?
