### ISSUE TITLE
Unify Docker images?

### ISSUE THREAD

**Issue by ddundo** [mesh-adaptation/docs#86]
While working on #83 and #85 I realised we're quite inefficient with our Docker management.

May I ask what was the idea behind separating PETSc and Firedrake images? Since we only use the PETSc image as a base for the Firedrake one, and we always deploy them at the same time, that is quite inefficient. I think it would be much better to unify them into one Dockerfile with a multi-stage build. Keeping them separated would make sense to me if, for example, we'd update the PETSc image less frequently than the Firedrake one (which might be sensible too?).

Also, installing UM2N and its dependencies now takes only about 20 seconds and ~1.5GB (which could probably be cut down too by cleaning up its dependencies, such as jupyter). But here it's more clear why it's separated

**Comment by jwallwork23** [comment]
To be honest, the only reason they are separate is because that's how they do it in Firedrake. AFAIK no one is using the PETSc container on it's own so I guess it would make sense to unify them.
