### ISSUE TITLE
Firedrake Docker build failed

### ISSUE THREAD

**Issue by ddundo** [mesh-adaptation/docs#93]
See https://github.com/mesh-adaptation/docs/actions/runs/12441054652

**Comment by jwallwork23** [comment]
Unfortunately the downside of combining steps into one big code block is that it becomes harder to debug when things go wrong.

**Comment by ddundo** [comment]
Yeah we could separate that final layer into two: one for installing Firedrake and one for the mesh adaptation software.

I see the Firedrake install script changed this week (https://github.com/firedrakeproject/firedrake/pull/3920/files#diff-d6c2e08efe7b22e4d96d12de5fa5edcd4aa9ded8f7cec61272fc23d1afaf0d3a) and I suspect it's something to do with setting MPI paths that's causing an error now.

I tried building locally now but I'm travelling and only have my M1 Mac with me, so I wasn't able to. Could you please take this on @jwallwork23 ?

**Comment by jwallwork23** [comment]
Ah okay. Sure, I can take it on.

**Comment by ddundo** [comment]
Thanks!

> Unfortunately the downside of combining steps into one big code block is that it becomes harder to debug when things go wrong.

It would be very useful to echo everything to console and not just the INFO level, especially since we can't access firedrake-install.log when building the image (I think? But either way)
